import {
  User,
  Code,
  FileText,
  Trophy,
  Mail,
  Edit,
  Plus,
  Trash,
  LogOut,
  Image,
  Award,
  Scroll,
  Medal,
  Star,
  Phone,
  MapPin,
  Download,
  FolderPlus,
  Linkedin,
  Github,
  Twitter,
  Instagram
} from "lucide-react";

export const SidebarIcons = {
  user: <User className="h-5 w-5" />,
  code: <Code className="h-5 w-5" />,
  file: <FileText className="h-5 w-5" />,
  trophy: <Trophy className="h-5 w-5" />,
  mail: <Mail className="h-5 w-5" />,
  edit: <Edit className="h-5 w-5" />,
  plus: <Plus className="h-5 w-5" />,
  trash: <Trash className="h-5 w-5" />,
  logout: <LogOut className="h-5 w-5" />,
  image: <Image className="h-5 w-5" />,
  award: <Award className="h-5 w-5" />,
  certificate: <Scroll className="h-5 w-5" />,
  medal: <Medal className="h-5 w-5" />,
  star: <Star className="h-5 w-5" />,
  phone: <Phone className="h-5 w-5" />,
  mapPin: <MapPin className="h-5 w-5" />,
  download: <Download className="h-5 w-5" />,
  folderPlus: <FolderPlus className="h-5 w-5" />,
  linkedin: <Linkedin className="h-5 w-5" />,
  github: <Github className="h-5 w-5" />,
  twitter: <Twitter className="h-5 w-5" />,
  instagram: <Instagram className="h-5 w-5" />
};
